workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    working_directory: pos
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS App
        script: |
          # For testing the build process without signing, use:
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - aliasgharinnocent@yahoo.com 
        notify:
          success: true
          failure: true
