// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk-MRinkLllu7KFNPcQFTVoxI4vyuKa_k',
    appId: '1:652844599136:web:db1227236645659ad9c005',
    messagingSenderId: '652844599136',
    projectId: 'point-of-sale-b7963',
    authDomain: 'point-of-sale-b7963.firebaseapp.com',
    storageBucket: 'point-of-sale-b7963.firebasestorage.app',
    measurementId: 'G-VMZEVM0LQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Nu90z3ynZy3F_GGZaI8pHCzbrbVHLOM',
    appId: '1:652844599136:android:b06f8702cc22914cd9c005',
    messagingSenderId: '652844599136',
    projectId: 'point-of-sale-b7963',
    storageBucket: 'point-of-sale-b7963.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6bSbyyb25Hujd14eerXYEgdNTxidr9Cs',
    appId: '1:652844599136:ios:b3bd71e2a8f3a7f9d9c005',
    messagingSenderId: '652844599136',
    projectId: 'point-of-sale-b7963',
    storageBucket: 'point-of-sale-b7963.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );
}
